name: "S3 File Upload"
description: "Upload an object to an S3 bucket."
author: "zdurham"
runs:
  using: docker
  image: Dockerfile
  env:
    AWS_IAM_TOKEN: "${AWS_IAM_TOKEN}"
branding:
  icon: arrow-up
  color: green
